-- ============================================================
-- PROJECT 2: WINDOWS DETECTION PLATFORM
-- PostgreSQL Database Schema
-- ============================================================

-- ============================================================
-- 1. RAW SYSMON EVENTS
-- Stores normalized Windows Sysmon telemetry
-- ============================================================

CREATE TABLE IF NOT EXISTS sysmon_events (
    id BIGSERIAL PRIMARY KEY,

    event_id INTEGER NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,

    computer_name TEXT,
    user_name TEXT,

    process_guid TEXT,
    process_id INTEGER,

    image TEXT,
    command_line TEXT,

    parent_image TEXT,
    parent_command_line TEXT,

    source_ip INET,
    source_port INTEGER,

    destination_ip INET,
    destination_port INTEGER,

    protocol TEXT,

    dns_query TEXT,
    dns_query_status INTEGER,

    target_object TEXT,

    hashes TEXT,

    raw_message TEXT,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. DETECTION ALERTS
-- Stores alerts generated by detection_engine.py
-- ============================================================

CREATE TABLE IF NOT EXISTS alerts (
    id BIGSERIAL PRIMARY KEY,

    event_id BIGINT REFERENCES sysmon_events(id) ON DELETE SET NULL,

    alert_name TEXT NOT NULL,

    severity TEXT NOT NULL,

    description TEXT,

    detection_source TEXT,

    rule_name TEXT,

    mitre_tactic TEXT,

    mitre_technique TEXT,

    confidence NUMERIC(5,2),

    status TEXT DEFAULT 'new',

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 3. DETECTION RULES
-- ============================================================

CREATE TABLE IF NOT EXISTS detection_rules (
    id BIGSERIAL PRIMARY KEY,

    rule_name TEXT UNIQUE NOT NULL,

    description TEXT,

    event_id INTEGER,

    severity TEXT,

    detection_logic TEXT,

    enabled BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 4. SIGMA RULES
-- ============================================================

CREATE TABLE IF NOT EXISTS sigma_rules (
    id BIGSERIAL PRIMARY KEY,

    rule_name TEXT UNIQUE NOT NULL,

    title TEXT,

    description TEXT,

    sigma_level TEXT,

    rule_content TEXT,

    mitre_tactic TEXT,

    mitre_technique TEXT,

    enabled BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 5. MITRE ATT&CK MAPPINGS
-- ============================================================

CREATE TABLE IF NOT EXISTS mitre_mappings (
    id BIGSERIAL PRIMARY KEY,

    alert_id BIGINT REFERENCES alerts(id) ON DELETE CASCADE,

    technique_id TEXT,

    technique_name TEXT,

    tactic TEXT,

    description TEXT,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 6. CASE / INVESTIGATION MANAGEMENT
-- ============================================================

CREATE TABLE IF NOT EXISTS investigation_cases (
    id BIGSERIAL PRIMARY KEY,

    case_number TEXT UNIQUE NOT NULL,

    title TEXT NOT NULL,

    description TEXT,

    severity TEXT,

    status TEXT DEFAULT 'open',

    assigned_to TEXT,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 7. CASE ↔ ALERT RELATIONSHIP
-- ============================================================

CREATE TABLE IF NOT EXISTS case_alerts (
    case_id BIGINT REFERENCES investigation_cases(id) ON DELETE CASCADE,

    alert_id BIGINT REFERENCES alerts(id) ON DELETE CASCADE,

    PRIMARY KEY (case_id, alert_id)
);

-- ============================================================
-- 8. SIEM EXPORT LOG
-- ============================================================

CREATE TABLE IF NOT EXISTS siem_exports (
    id BIGSERIAL PRIMARY KEY,

    event_id BIGINT REFERENCES sysmon_events(id) ON DELETE SET NULL,

    export_type TEXT,

    destination TEXT,

    export_status TEXT,

    exported_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_sysmon_events_event_id
ON sysmon_events(event_id);

CREATE INDEX IF NOT EXISTS idx_sysmon_events_event_time
ON sysmon_events(event_time);

CREATE INDEX IF NOT EXISTS idx_sysmon_events_image
ON sysmon_events(image);

CREATE INDEX IF NOT EXISTS idx_sysmon_events_user
ON sysmon_events(user_name);

CREATE INDEX IF NOT EXISTS idx_sysmon_events_destination_ip
ON sysmon_events(destination_ip);

CREATE INDEX IF NOT EXISTS idx_sysmon_events_dns_query
ON sysmon_events(dns_query);

CREATE INDEX IF NOT EXISTS idx_alerts_severity
ON alerts(severity);

CREATE INDEX IF NOT EXISTS idx_alerts_status
ON alerts(status);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at
ON alerts(created_at);

CREATE INDEX IF NOT EXISTS idx_mitre_technique
ON mitre_mappings(technique_id);
